Feature/password recovery
Tempname256113/inctagram_back pull request #5
Opened 2023-12-17 19:16 UTC by ArtyomSunRise

2023-12-17 19:38 UTC, Tempname256113 commented on prisma/schema.prisma
> +}
здесь оставить только id, userId и создать свойство содержащее uuid. по uuid мы будем удалять сессии с которых делается логаут чтобы не выключать сразу все, а выборочно. по userId и uuid

2023-12-17 20:42 UTC, Tempname256113 requested changes

2023-12-17 20:42 UTC, Temp256113 commented on prisma/schema.prisma
> +model ChangePasswordRequest {
не совсем понял к чему эта таблица здесь вообще. если нужно записать информацию о том что юзер захотел поменять пароль то добавляем в userAdditionalInfo какой нибудь passwordRecoveryStatus: boolean

если оставляем таблицу то менять надо userAdditionalInfo в userEmailInfo, а эту таблицу в userPasswordRecovery и оставляем пока одну строку recoveryStatus: boolean

если recoveryStatus: true значит юзер запросил смену пароля и ему отправилось сообщение на почту. если false значит пароль менять не хочет и так норм

2023-12-17 20:42 UTC, Tempname256113 commented on apps/first-app/src/change-password-request/change-password-request.service.ts
> +  async create(createChangePasswordRequestDTO: CreateChangePasswordRequestDTO) {
я думаю создавать отдельный модуль для всего одного действия (сменить пароль) это слишком. это просто логика которая должна остаться в handler'e и не больше. не нужно слишком на многие части приложение растягивать

предлагаю сделать логику и запрос в бд в хендлере где запрос на смену пароля (вообще запросы в бд делаться должны на отдельном уровне конечно, в репозитории. потом сделаю репозиторий)

2023-12-17 20:42 UTC, Tempname256113 commented on apps/first-app/src/user/user.service.ts
> +  async findUserByEmail(email: string) {
тоже как то лучше такие вещи в одном месте держать. где это используется там я думаю надо написать про юзера. если ты хочешь просто вынести запросы на отдельный уровень то надо делать репозиторий. давай первым делом тогда сделаем уровень DAL и оттуда уже будем запросы делать к базе данных. когда доделаем основной флоу и останется интеграция со сторонними апи (гугл, гит) надо будет сделать отдельный слой для работы с бд

2023-12-17 20:42 UTC, Tempname256113 commented on libs/shared/src/constants/errors.constants.ts
> +export const USER_ERRORS = {
почему не enum если это обычное перечисление?

2023-12-17 20:42 UTC, Tempname256113 commented on apps/first-app/src/auth/dto/password-recovery.dto.ts
> +  token: string;
token не в req body приходит, а в headers authorization bearer обычно

2023-12-17 21:01 UTC, ArtyomSunRise commented on apps/first-app/src/auth/dto/password-recovery.dto.ts
> +  token: string;
Это не авторищационный токен

2023-12-17 21:02 UTC, ArtyomSunRise commented on libs/shared/src/constants/errors.constants.ts
> +export const USER_ERRORS = {
Потому что enum немного для другого, с моей точки зрения)

2023-12-17 21:03 UTC, ArtyomSunRise commented on apps/first-app/src/change-password-request/change-password-request.service.ts
> +  async create(createChangePasswordRequestDTO: CreateChangePasswordRequestDTO) {
Согласен

2023-12-18 08:03 UTC, Tempname256113 commented on apps/first-app/src/auth/dto/password-recovery.dto.ts
> +  token: string;
а что это?

2023-12-18 08:04 UTC, Tempname256113 commented on libs/shared/src/constants/errors.constants.ts
> +export const USER_ERRORS = {
enum нужен для перечисления примитивов. тут оно и есть впринципе)

2023-12-18 11:19 UTC, ArtyomSunRise commented on apps/first-app/src/auth/dto/password-recovery.dto.ts
> +  token: string;
Посмотри в коде, там же все понятно

2023-12-18 11:20 UTC, ArtyomSunRise commented on apps/first-app/src/auth/dto/password-recovery.dto.ts
> +  token: string;
Это токен, который с имэйла приходит

2023-12-18 11:50 UTC, Tempname256113 commented on apps/first-app/src/auth/dto/password-recovery.dto.ts
> +  token: string;
может тогда его назвать passwordRecoveryCode

2023-12-23 15:46 UTC, merged